### ISSUE TITLE
Add range-loop based iterators

### ISSUE THREAD

**Issue by sticilface** [rlogiacco/CircularBuffer#20]
Any chance of adding compatibility for c++11 range loops? 

Id like to be able to iterate over the data using 

```cpp

for (auto & item : cirBuffer ) 
{
...
}
```

thanks

**Comment by rlogiacco** [comment]
You can submit a pull request containing the necessary changes, but as this library is intended for limited memory devices, watch out for any increment on program space or memory use: we strive for efficiency, not all around ease of use.

**Comment by rlogiacco** [comment]
Closing due to lack of feedback
