### ISSUE TITLE
CircularBuffer.ino doesn't compile with Arduino 1.8.13

### ISSUE THREAD

**Issue by soundmasteraj** [rlogiacco/CircularBuffer#36]
Error Template Argument 3 when Compiling for Digispark 16.5
No Error Arduino 1.8.12 when compiling for Uno.

**Comment by rlogiacco** [comment]
Does it compile for Arduino Uno on 1.8.13?

**Comment by drbrodie** [comment]
I have also experienced a failure to compile with Arduino 1.8.13 for a Sparkfun Artemis Redboard though it did previously compile for that board on an older version of Arduino (sorry - I don't recall which).  It did compile though with 1.8.13 for Arduino Mega.

**Comment by rlogiacco** [comment]
As I don't have those boards, unless you can contribute patches I guess I have no choice but to leave those out of the supported platforms
