### ISSUE TITLE
Can't use library within a class.

### ISSUE THREAD

**Issue by gnalbandian** [rlogiacco/CircularBuffer#47]
Hi.
I am trying to use this library as an object within a class and I am getting the following error:

` error: use of deleted function 'constexpr CircularBuffer<timeTempStruct, 10u>::CircularBuffer(const CircularBuffer<timeTempStruct, 10u>&)'`

The class is globally instanced as:

`className objectName[8] = className (constructor arguments);`

Any tip on how to make this work?
Thanks!

Regards!
Gonzalo

**Comment by gnalbandian** [comment]
Solved by not using copy constructor when instantiating the class.

**Comment by dzalf** [comment]
@gnalbandian Sorry for reviving this thread so late. How exactly did you manage to solve this?

I am facing exactly the same issue:

<img width="795" alt="image" src="https://github.com/rlogiacco/CircularBuffer/assets/3759916/f6b62061-c0ef-49dd-9927-6d05bfa4ace9">
