### ISSUE TITLE
bug:Memory trample

### ISSUE THREAD

**Issue by xiaofyao** [rlogiacco/CircularBuffer#65]
When the capacity is set to 0, memory will stampede when pushing data:

CircularBuffer<MsgInfo,0> m_ring_msg_priority_low;
m_ring_msg_priority_low.push(msg);

**Comment by rlogiacco** [comment]
And what would be reason for setting the capacity to 0? In your shoes I would be happy the program didn't crash on startup...

Do you have a suggestion on how to properly handle this condition?

**Comment by xiaofyao** [comment]
I think there should be a limit that denies user operations if the capacity is 0.
Whatever the user does should not result in a high risk of memory stampede.

Br,
xiaofyao
