### ISSUE TITLE
Remove item from the middle of the buffer

### ISSUE THREAD

**Issue by guilhermeaiolfi** [rlogiacco/CircularBuffer#66]
Hi,

I've just discovered this library yesterday and I am trying to use it my project. And I've read the other issues and what I am going to ask is something that was describe as absurd, as the title of this issues gives away: I need to remove an item that is not the head or tail. 

The use case is very simple, someone can ask about something and it goes to the queue, but it can also cancel de order. So I need to remove that item from the queue before it gets processed. Does that make sense? Is there any workaround it today?

Thanks.

**Comment by digamesystems** [comment]
I'm not sure how to pull an item out of the middle of the buffer, but you can choose whether or not to process an item at the time it's about to be dealt with.

In my application I'm queueing up messages to be sent to a server. If the attempt to sends them succeeds, I take the message out of the buffer. If it fails I hang onto it for a later attempt. (It's a mobile app where connectivity is spotty.)

Snippet from my code: 
```
      String activeMessage = String(msgBuffer.first()->c_str());   // Read from the buffer without removing the data from it.
      
      messageACKed = sendReceiveLoRa(activeMessage, config); // Try to send the message over a wireless link

      ...

      if (messageACKed)   // Message sent and reply received. Take it off of the queue.
      {
        ...
        String  * entry = msgBuffer.shift(); // Pops the message off of the queue.
        delete entry;
        ...
     }
```

**Comment by guilhermeaiolfi** [comment]
But them I will need two queues: one to be processed and one to hold that items that shouldn't be processed. That doesn't look right. Anyway, I came up with a workaround that worked. It is basically looping thought all items and putting them back at the end of the buffer, except the one I want to remove. It seems good enough for the time being.

**Comment by digamesystems** [comment]
I’m not sure what your data structure looks like, but if you have the option, you might consider using a ‘toBeProcessed’ flag on each entry that you could toggle on the fly. That way you could avoid a second queue.

‘Sounds like you’ve got it under control, though.

Cheers!

John M. Price, Ph.D.
Digame Systems<diagamesystems.com> | 88 E San Fernando St. Ste. 1511, San Jose CA, 95113 | 408.840.9871 |

**Comment by rlogiacco** [comment]
I don't see the feature you are requesting as something required on a circular buffer, thus I don't see it as a defect. 
My reasoning is this is a buffer, not a data archive: the data are intended to be added and removed from the buffer, not manipulated "in place". Nothing prevents you to manipulate the data stored in the buffer, but the features you are requesting are intended for a list, a vector, an hashmap.... not a buffer.
