### ISSUE TITLE
How can I Declare CircularBuffer variable first and initialize later?

### ISSUE THREAD

**Issue by chenscottus** [rlogiacco/CircularBuffer#74]
How can I Declare  variable first and initialize later?
like this:
      CircularBuffer cb_variable;

      cb_variable = CircularBuffer<int, 100>;

How can I Declare a CircularBuffer pointer and point to a CircularBuffer object?
      CircularBuffer * cb_variable_ptr;

     cb_variable_ptr = &CircularBuffer<int, 100>;

Many thanks!

**Comment by juuldiksWF** [comment]
I'm currently facing the same issue.

Any help would be much appriciated!
